{
 "title": "🔴 RED Metrics - Request / Error / Duration",
 "tags": [
  "red",
  "sre",
  "request-error-duration",
  "otel"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "📥 Request Rate per Route",
   "type": "timeseries",
   "description": "Request rate per endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "🚨 5xx Error Rate per Route",
   "type": "timeseries",
   "description": "5xx errors per endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_status_code=~\"5..\"}[1m])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "⏱️ Response Duration p95 per Route",
   "type": "timeseries",
   "description": "Average response duration per endpoint (p95)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[1m])) by (le, http_route)) * 1000",
     "legendFormat": "{{http_route}} p95"
    }
   ]
  }
 ]
}